model_param:
    batch_size: 512
    vocab_size: 800000
    num_layers: 2
    layer_size: 19968
    projection: 2048
    seq_len: 20
    num_gates: 4
    num_non_linear: 5
    num_add: 8
    data_scale: 100 

sw_param:
    kernel_launch_overhead: 9e-6 #9us
    precision: 2

tech_param:
    core:
        nominal_power_per_mcu: 0.13 #W
        nominal_flop_rate_per_mcu: 128
        nominal_area_per_mcu: 0.38 #mm^2
        nominal_frequency: 1.33e9 #Hz
        nominal_voltage: 0.8 
        threshold_voltage: 0.2 
        margin_voltage: 0.35
        operating_area_per_mcu: 0.11
        num_mcu_per_bundle: 8 #a bundle can be thought of as SM, number of tensorcores per SM
        FMA_width: 4            #4 for tensorcore enabled (implying 4x4 systolic array) and 1 for tensorcore disabled
        dataflow: "best"        #{wst. ast, ost, best, none}: wst: weight stationary, ast: activation stationary, ost: output stationary
        util: 0.85 #util should be 0.75 (12/16) for tensorcore
    DRAM:
        dynamic_energy_per_bit: 4.2e-12
        static_power_per_bit: 0.6e-12
        area_per_bit: 11e-10 #mm2
        stack_capacity: 24 GB
        area_per_stack: 100 #mm2
        latency: 100e-9
        mem_ctrl_area: 5 #mm2 
        nominal_frequency: 1.38e9
        nominal_voltage: 1.2
        threshold_voltage: 0.4 
        margin_voltage: 0.6
        max_voltage: 1.8
        num_links_per_mm: 400
        num_links_per_stack: 1024
        util: 1
    SRAM-L2:
        dynamic_energy_per_bit: 3.5e-15
        static_power_per_bit: 8.4e-12
        area_per_bit: 6.4e-8 #mm2
        bank_capacity: 32 KB
        controller_area_per_link: 0.004 #mm2 
        controller_power_per_link: 0.04 #W
        latency: 0
        overhead: 0.20 #20% circuitry overhead in cell area
        util: 0.45
    SRAM-L1:
        dynamic_energy_per_bit: 2e-15
        static_power_per_bit: 8e-12
        area_per_bit: 8e-8 #mm2
        bank_capacity: 32 KB
        controller_area_per_link: 0.004 #mm2 
        controller_power_per_link: 0.04 #W
        latency: 0
        overhead: 0.20
        util: 1
    SRAM-R:
        dynamic_energy_per_bit: 2e-15
        static_power_per_bit: 9e-12
        area_per_bit: 8e-8 #mm2
        bank_capacity: 16 KB
        controller_area_per_link: 0.00 #mm2 
        controller_power_per_link: 0.0 #W
        latency: 0 
        overhead: 0.25
        util: 1 
    network:
        intra_node:
          latency: 5e-6 
          nominal_frequency: 3e9
          nominal_voltage: 1
          nominal_energy_per_link: 1e-12
          nominal_area_per_link: 100e-6 #mm^2
          num_links_per_mm: 400
          threshold_voltage: 0.25
          margin_voltage: 0.45
          util: 1
        inter_node:
          latency: 5e-6
          nominal_frequency: 20e9
          nominal_voltage: 1.2
          nominal_energy_per_link: 13e-12
          nominal_area_per_link: 0.045
          num_links_per_mm: 20 #Assuming 4 layers on PCB and 200 um pitch for high speed signalling
          threshold_voltage: 0.35
          margin_voltage: 0.5
          util: 0.96
area_breakdown:
    device_area_budget: 1230 #mm2
    proc_chip_area_budget: 815 #mm2
    core: 0.3
    L2: 0.08062
    L1: 0.102
    reg_mem: 0.022
    DRAM: 0.0248
    network:
      intra_node: 0.1
      inter_node: 0.1

power_breakdown:
    TDP: 300
    core: 0.3745
    DRAM: 0.16
    L2: 0.000217
    L1: 0.0016
    reg_mem: 0.0055
    network:
      intra_node: 0.1
      inter_node: 0.1

perimeter_breakdown:
    DRAM: 0.5
    inter_node: 0.3
    intra_node: 0.2

system_hierarchy:
    num_devices_per_node: 4
    num_nodes: 1
    inter_derate: 1
    intra_derate: 1
    kp1_inter: False
    kp2_inter: False
    dp_inter: False
    lp_inter: False

network_topology:
    inter_node: "hic" #mesh, torus, crossbar, custom, hierarchical
    intra_node: "none"

memory_hierarchy:
    l0: #Register Memory
      type: "SRAM-R"
      scope: "mcu"
    l1: #Shared Memory
      type: "SRAM-L1"
      scope: "mcu-bundle"
    l2: #L2 
      type: "SRAM-L2"
      scope: "global"
    l3: #Global Memory
      type: "DRAM"
      scope: "global" 

scheduling_param:
    auto: False 
    dp: 4
    lp: 1
    kp_hidden_dim1: 1
    kp_hidden_dim2: 1
    kp_softmax_dim1: 1
    kp_softmax_dim2: 1
    kp_embedding_dim1: 1
    kp_embedding_dim2: 1
    kp_projection_dim1: 1
    kp_projection_dim2: 1
    kp_hidden_type: -1
    kp_softmax_type: -1
    kp_embedding_type: -1
    kp_projection_type: -1
